
`rust` 中没有异常。 `js` 中是 `try{} catch() {}`

Rust 中两种不同类型的错误处理：`panic` 和 `Result`。


## 捕获错误

处理 `Result` 类型最直接的方式是使用 `match` 表达式，这类似于其他语言中 `try/catch`：


##  `Result` 别名

## 错误打印


## 错误传播

`Rust` 中有个 `?` 操作符，用于向上传播错误。主要的应用场景是，当我们调用函数遇到错误，但又不想立即处理，只是想把这个错误继续往外传播，让最外层的调用者处理

## 处理不同类型错误

有时候，在一个函数中会遇到多种类型的错误，而函数的返回类型是固定的，如果我们使用 `?` 向上传播错误就会遇到问题，错误类型不匹配


这里介绍一种错误的处理方法，`Rust` 标准库中的所有错误都可以转换为 `Box<dyn std::error::Error + Send + Sync + 'static>` 类型，其中：

- `dyn std::error::Error`：表示任意错误；
    
- `Send + Sync + 'static`：能够在多线程之间安全传递；


## 忽略错误

可以使用 `let _ = ...` 消除这个告警

## 错误定义